import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/header/Navbar";

import { Providers } from "../../providers/Providers"; // Import the client-side provider
import SideBar from "@/components/sidebar/SideBar";
import { ReactNode } from "react";
import { Cairo } from "next/font/google";

const cairo = Cairo({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], // choose what you need
    variable: "--font-cairo",
}); 



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
    params: Promise<{ lang: string }>; // 👈 params is a Promise now
}) {
 const { lang } = await params; // 👈 await it
  const dir = lang === "ar" ? "rtl" : "ltr";
  return (
    <html lang={lang} dir={dir} className={cairo.variable}>
      <body >
        {/* suppressHydrationWarning */}
        <Providers>
          <div className="flex h-screen">
            {/* Sidebar */}
            <div className="w-60 shrink-0 ">
              <SideBar />
            </div>
            {/* Main */}
            <div className="flex flex-col flex-1 min-w-0">
              {/* Header */}
              <Navbar />
              {/* Content */}
              <main className="flex-1 overflow-y-auto p-4 mainBackGroundColor">
                {children}
              </main>
              {/* Footer */}
              <footer className="h-10 bg-white border-t flex items-center justify-center text-sm text-gray-500">
                © {new Date().getFullYear()} My Dashboard
              </footer>
            </div>

          </div>

        </Providers>
      </body>
    </html>
  );
}
